language: ruby
sudo: false
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1

gemfile:
  - gemfiles/Gemfile-rails4.1.x
  - gemfiles/Gemfile-rails4.2.x
  - gemfiles/Gemfile-rails5.0.x

before_script:
  - 'cd test/dummy; rake db:migrate; rake db:test:prepare; cd ../..'

notifications:
  email: false
